services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    
    ports:
      - "80:80"
    
    volumes:
      - /opt/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - /opt/docker/nginx/html:/usr/share/nginx/html:ro
    
    networks:
      - proxy

networks:
  proxy:
    name: proxy

