- name: Configure Admin Users
  hosts: all
  become: true

  vars_files:
    - ../vars/users_vault.yml

  tasks:
    - name: Ensure sudo is installed
      ansible.builtin.apt:
        name: sudo
        state: present
        update_cache: true

    - name: Create adminja account
      ansible.builtin.user:
        name: adminja
        password: "{{ vault_adminja_password_hash }}"
        groups:
          - sudo
        append: true
        shell: /bin/bash
        create_home: true
        state: present
        update_password: on_create

    - name: Install SSH public key for adminja
      ansible.posix.authorized_key:
        user: adminja
        state: present
        key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_ed25519.pub') }}"

    - name: Create .hushlogin for adminja
      ansible.builtin.copy:
        content: ""
        dest: /home/adminja/.hushlogin
        owner: adminja
        group: adminja
        mode: "0644"
        force: false

    - name: Enable color Bash prompt
      ansible.builtin.lineinfile:
        path: /home/adminja/.bashrc
        regexp: '^#?force_color_prompt=yes'
        line: 'force_color_prompt=yes'


