- import_playbook: ../common/system_utils.yml
- import_playbook: ../users.yml
- import_playbook: ../modules/neovim.yml
- import_playbook: ../services/docker.yml

- name: Configure Nginx on Droplet
  hosts: all
  become: true

  roles:
    - role: nginx
      nginx_profile: nyxquant
